Dims pages creation 2
Dev-incubator/DIMS.UI-9 pull request #2
Opened 2020-09-16 16:00 UTC by artur-nikitsin

Create 'Tasks', 'Task Track' commponents; user register and edit modals. Add Firebase Api data functions.

2020-09-19 21:35 UTC, maximsan requested changes
Hello! Looks good. Please, fix notes. Thanks!

2020-09-19 21:35 UTC, maximsan commented on src/components/MemberProfile/MemberProfile.js
> +class MemberProfile extends React.Component {
you can use PureComponent here, https://ru.reactjs.org/docs/react-api.html#reactpurecomponent

2020-09-19 21:35 UTC, maximsan commented on src/components/MemberProfile/MemberProfile.js
> +          className={this.state.activePage === 'taskTrack' ? 'activeTracksButton' : 'tracksButton'}
you can make it more generic by using boolean flag `isActive` and adding `active` class depending on it in template expression

2020-09-19 21:35 UTC, maximsan commented on src/components/MemberProfile/MemberProfile.js
> +    }
It simple condition. It's not need in switch-case, just use ternary operator instead

2020-09-19 21:35 UTC, maximsan commented on src/components/MemberProfile/membersProfile.scss
> +@import '../common/Styles/Buttons/simpleButton';
you can move common styles like mixins in one common file `mixins` and according folder

2020-09-19 21:35 UTC, maximsan commented on src/components/MemberTracks/MemberTracks.js
> +                <a href=''>{track.trackNote.substr(0, 50) + '...'}</a>
create a helper method and unit-tests for it

2020-09-19 21:35 UTC, maximsan commented on src/components/MemberTracks/MemberTracks.js
> +              <td>{new Date(track.trackDate).toLocaleDateString()}</td>
create a helper method and unit-tests for it

2020-09-19 21:35 UTC, maximsan commented on src/components/MemberTracks/MemberTracks.js
> +        if (this.state.userTrackList === null) {
use `!` here

2020-09-19 21:35 UTC, maximsan commented on src/components/MemberTracks/MemberTracks.js
> +          <p className={'userGreeting'}>{'Hi, dear ' + this.props.userName + '! This is your task tracks:'}</p>
use template literals here, https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/template_strings

2020-09-19 21:35 UTC, maximsan commented on src/components/Members/MembersPage.js
> +      case 'newMembersTable':
Actually, it's better to use map objects to reduce possibility to create mistake by writing every string in every place by hands, like
`const tables = {
    membersTable: 'membersTable',
    ....
}`

2020-09-19 21:35 UTC, maximsan commented on src/components/Members/MembersPage.js
> +    });
use `handleCloseModal ()` here

2020-09-19 21:35 UTC, maximsan commented on src/components/Members/MembersPage.js
> +    } else return null;
add brackets, please

2020-09-19 21:35 UTC, maximsan commented on src/components/MembersTasks/Buttons/buttons.scss
> +  min-height: 30px;
use rem for adaptive design

2020-09-19 21:35 UTC, maximsan commented on src/components/Modals/Common/Modal.js
> +        {this.props.loading ? (
use spread operator https://codeburst.io/a-simple-guide-to-destructuring-and-es6-spread-operator-e02212af5831

2020-09-19 21:35 UTC, maximsan commented on src/components/Modals/Common/UsersModalDataWorker.js
> +                onChange={(event) => this.handleChange(event, 'firstName')}
handleChange already has access to event

2020-09-19 21:35 UTC, maximsan commented on src/components/Modals/Common/UsersModalDataWorker.js
> +      [input]: event.target.value,
event is enough to retrieve name and value

2020-09-19 21:35 UTC, maximsan commented on src/components/Modals/Common/UsersModalDataWorker.js
> +                value={this.state.firstName ? this.state.firstName : ''}
` this.state.firstName || '' `

2020-09-19 21:35 UTC, maximsan commented on src/components/Modals/Common/UsersModalDataWorker.js
> +                type='text'
create custom text input component

2020-09-19 21:35 UTC, maximsan commented on src/components/Modals/Common/UsersModalDataWorker.js
> +                id='userAdress'
use name instead of id

2020-09-19 21:35 UTC, maximsan commented on src/components/Modals/Common/modal.scss
> +    align-items: center;
it seems like a mixin candidate

2020-09-19 21:35 UTC, maximsan commented on src/components/Modals/UserRegisterModal/UserRegisterModal.js
> +class UserRegisterModal extends React.Component {
it's just a function right now

2020-09-19 21:35 UTC, maximsan commented on src/firebase/apiSet.js
> +          skype: data.skype,
I guess you can re-use it as a method

2020-09-20 13:20 UTC, artur-nikitsin commented on src/components/MemberProfile/MemberProfile.js
> +class MemberProfile extends React.Component {
Fixed

2020-09-20 13:40 UTC, artur-nikitsin commented on src/components/MemberProfile/MemberProfile.js
> +    }
Fixed

2020-09-20 13:43 UTC, artur-nikitsin commented on src/components/MemberTracks/MemberTracks.js
> +        if (this.state.userTrackList === null) {
Fixed

2020-09-20 13:45 UTC, artur-nikitsin commented on src/components/MemberTracks/MemberTracks.js
> +          <p className={'userGreeting'}>{'Hi, dear ' + this.props.userName + '! This is your task tracks:'}</p>
Fixed

2020-09-20 13:48 UTC, artur-nikitsin commented on src/components/Members/MembersPage.js
> +    } else return null;
Fixed

2020-09-20 14:01 UTC, artur-nikitsin commented on src/components/Modals/Common/UsersModalDataWorker.js
> +                onChange={(event) => this.handleChange(event, 'firstName')}
I used this syntax to pass another argument to the handler function...

2020-09-20 14:18 UTC, artur-nikitsin commented on src/components/Modals/Common/UsersModalDataWorker.js
> +      [input]: event.target.value,
Fixed

2020-09-20 14:23 UTC, artur-nikitsin commented on src/components/Modals/Common/UsersModalDataWorker.js
> +                value={this.state.firstName ? this.state.firstName : ''}
Fixed

2020-09-20 14:28 UTC, artur-nikitsin commented on src/components/Modals/Common/UsersModalDataWorker.js
> +                id='userAdress'
Fixed

2020-09-20 15:01 UTC, artur-nikitsin commented on src/components/Modals/Common/UsersModalDataWorker.js
> +                type='text'
Fixed

2020-09-20 15:03 UTC, artur-nikitsin commented on src/components/Modals/UserRegisterModal/UserRegisterModal.js
> +class UserRegisterModal extends React.Component {
Fixed

2020-09-20 15:15 UTC, artur-nikitsin commented on src/firebase/apiSet.js
> +          skype: data.skype,
Fixed

2020-09-20 15:18 UTC, artur-nikitsin commented on src/components/MembersTasks/Buttons/buttons.scss
> +  min-height: 30px;
Fixed

2020-09-20 15:20 UTC, artur-nikitsin commented on src/components/Members/MembersPage.js
> +    });
Fixed

2020-09-20 15:25 UTC, artur-nikitsin commented on src/components/Members/MembersPage.js
> +      case 'newMembersTable':
Fixed

2020-09-20 15:48 UTC, artur-nikitsin commented on src/components/MemberProfile/membersProfile.scss
> +@import '../common/Styles/Buttons/simpleButton';
Fixed

2020-09-20 16:05 UTC, artur-nikitsin commented on src/components/Modals/Common/modal.scss
> +    align-items: center;
Fixed

2020-09-20 17:25 UTC, artur-nikitsin commented on src/components/MemberTracks/MemberTracks.js
> +                <a href=''>{track.trackNote.substr(0, 50) + '...'}</a>
Fixed

2020-09-23 06:28 UTC, artur-nikitsin commented on src/components/MemberTracks/MemberTracks.js
> +              <td>{new Date(track.trackDate).toLocaleDateString()}</td>
Fixed

2020-09-23 07:03 UTC, artur-nikitsin commented on src/components/MemberProfile/MemberProfile.js
> +          className={this.state.activePage === 'taskTrack' ? 'activeTracksButton' : 'tracksButton'}
I don’t understand where I should toggle this flag

2020-09-24 14:53 UTC, maximsan requested changes
Hello! I left a lot of notes. Be accurate and try to fix all of them ASAP. Thanks! Good shot!

2020-09-24 14:53 UTC, maximsan commented on public/index.html
> +    <title>DIMS-2020</title>
it's better to make it dynamic, think how to do it :)

2020-09-24 14:53 UTC, maximsan commented on src/App.js
> +class App extends React.Component {
use PureComponent :)

2020-09-24 14:53 UTC, maximsan commented on src/components/AppContainer/AppContainer.js
> +class AppContainer extends React.Component {
use PureComponent

2020-09-24 14:53 UTC, maximsan commented on src/components/AppContainer/AppContainer.js
> +  };
When are you going to rewrite it ? or did you forget about it ?

2020-09-24 14:53 UTC, maximsan commented on src/components/Footer/Footer.js
> +    <p className='allRights'>DIMS-2020. All rights reversed ©</p>
The same is here. Please, do date dynamic, not hardcoded.

2020-09-24 14:53 UTC, maximsan commented on src/components/Header/Header.js
> +      {props.isLogin ? <button className='logoutButton' onClick={props.handleLogout}>Logout</button> : null}
I guess, it can be just `props.isLogin && <button className='logoutButton' onClick={props.handleLogout}>Logout</button>`

2020-09-24 14:53 UTC, maximsan commented on src/components/LoginForm/LoginForm.js
> +          <li><label htmlFor="">Password:</label><input type="password" /></li>
create custom input with label component

2020-09-24 14:53 UTC, maximsan commented on src/components/LoginForm/LoginForm.js
> +                     onClick={props.handleLogin} /></li>
create submit button component

2020-09-24 14:53 UTC, maximsan commented on src/components/LoginForm/LoginForm.js
> +function LoginForm(props) {
spread `handleLogin` from props right here

2020-09-24 14:53 UTC, maximsan commented on src/components/LoginForm/loginForm.scss
> +      input {
for the better usability try  do not to use tags

2020-09-24 14:53 UTC, maximsan commented on src/components/MemberTracks/MemberTracks.js
> +class MemberTracks extends React.Component {
use PureComponent

2020-09-24 14:53 UTC, maximsan commented on src/components/MemberTracks/MemberTracks.js
> +
remove indentation

2020-09-24 14:53 UTC, maximsan commented on src/components/MemberTracks/MemberTracks.js
> +                <a href=''>{track.name}</a>
remove a if you don't need a link

2020-09-24 14:53 UTC, maximsan commented on src/components/MemberTracks/MemberTracks.js
> +          <p className={"userGreeting"}>{`Hi, dear '${this.props.userName}! This is your task tracks:`}</p>
remove brackets

2020-09-24 14:53 UTC, maximsan commented on src/components/Members/MembersPage.js
>  class MembersPage extends React.Component {
use PureComponent

2020-09-24 14:53 UTC, maximsan commented on src/components/Members/MembersPage.js
> +      if (status === 'OK') {
It seems redundant, if you here that your promise was resolved as 'OK'

2020-09-24 14:53 UTC, maximsan commented on src/components/Modals/Common/ModalElements/RadioInput.js
> +        /*  className={`radioInput ${this.props.status}`}*/
remove

2020-09-24 14:53 UTC, maximsan commented on src/components/Modals/Common/ModalElements/RadioInput.js
> +          onChange={this.props.handleRadioInput}
spread props

2020-09-24 14:53 UTC, maximsan commented on src/components/Modals/Common/ModalElements/TextInput.js
> +
spread props

2020-09-24 14:53 UTC, maximsan commented on src/components/Modals/Common/ModalElements/TextInput.js
> +        this.props.handleValidInput(this.props.inputName, validatorsManager(this.props.inputName, this.props.value).isValid);
split in several steps, make code readable

2020-09-24 14:53 UTC, maximsan commented on src/components/Modals/Common/ModalElements/TextInput.js
> +          status: validatorsManager(this.props.inputName, this.props.value).status
split in several steps, make code readable and use short object props

2020-09-24 14:53 UTC, maximsan commented on src/components/Modals/Common/ModalElements/TextInput.js
> +
do props spreading

2020-09-24 14:53 UTC, maximsan commented on src/components/Modals/Common/UsersModalDataWorker.js
> +        skype: this.props.userData.skype
maybe create a helper for it? you component will be smaller

2020-09-24 14:53 UTC, maximsan commented on src/components/Modals/Common/UsersModalDataWorker.js
> +      [event.target.name]: event.target.value,
do event spreading

2020-09-24 14:53 UTC, maximsan commented on src/components/Modals/Common/UsersModalDataWorker.js
> +    }
create a helper for it with unit tests

2020-09-24 14:53 UTC, maximsan commented on src/components/Modals/Common/UsersModalDataWorker.js
> +        });
what about error catching ?

2020-09-24 14:53 UTC, maximsan commented on src/components/Modals/Common/UsersModalDataWorker.js
> +                       isSubmit={this.state.isSubmit} />
maybe do it with loop through array?

2020-09-24 14:53 UTC, maximsan commented on src/components/Modals/Common/UsersModalDataWorker.js
> +                       isSubmit={this.state.isSubmit} />
maybe do it with loop through array?

2020-09-24 14:53 UTC, maximsan commented on src/components/Sidebar/SideBar.js
> +function SideBar(props) {
spread props

2020-09-24 14:53 UTC, maximsan commented on src/components/helpers/getLocaleDate/getLocalDate.js
> +import React from "react";
remove

2020-09-24 14:53 UTC, maximsan commented on src/components/helpers/getLocaleDate/getLocalDate.test.js
> +import React from "react";
remove

2020-09-24 14:53 UTC, maximsan commented on src/components/helpers/getLocaleDate/getLocalDate.test.js
> +    //Assert - checking
remove

2020-09-24 14:53 UTC, maximsan commented on src/components/helpers/getSubString/getSubString.js
> +import React from 'react';
remove

2020-09-24 14:53 UTC, maximsan commented on src/components/helpers/getSubString/getSubString.test.js
> +import React from "react";
remove

2020-09-24 14:53 UTC, maximsan commented on src/components/helpers/validators/lengthValidator.js
> +  if (props.length > 2) {
pass just length, why do you need props ?

2020-09-24 14:53 UTC, maximsan commented on src/components/helpers/validators/lengthValidator.js
> +import React from "react";
remove

2020-09-24 14:53 UTC, maximsan commented on src/components/helpers/validators/lastNameValidator.js
> +function lastNameValidator(props) {
do you need all props ?, don't forget about unit-tests

2020-09-24 14:53 UTC, maximsan commented on src/components/helpers/validators/emailValidator.js
> +function emailValidator(props) {
do you need all props ?, don't forget about unit-tests

2020-09-24 14:53 UTC, maximsan commented on src/components/helpers/validators/mobilePhoneValidator.js
> +    if (regExpTester(phoneNumberRegexp, props)) {
do you need all props ?, don't forget about unit-tests

2020-09-24 14:53 UTC, maximsan commented on src/components/helpers/validators/nameValidator.js
> +    if (regExpTester(nameRegexp, props)) {
do you need all props ?, don't forget about unit-tests

2020-09-24 14:53 UTC, maximsan commented on src/components/helpers/validators/regExpTester.js
> +};
don't forget about unit-tests

2020-09-24 14:53 UTC, maximsan commented on src/components/helpers/validators/validatorsManager.js
> +}
don't forget about unit-tests, but it's not clear how to test it properly...  think about it :)

2020-09-24 17:23 UTC, artur-nikitsin commented on public/index.html
> +    <title>DIMS-2020</title>
Fixed

2020-09-24 17:24 UTC, artur-nikitsin commented on src/App.js
> +class App extends React.Component {
Fixed

2020-09-24 17:24 UTC, artur-nikitsin commented on src/components/AppContainer/AppContainer.js
> +class AppContainer extends React.Component {
Fixed

2020-09-24 17:27 UTC, artur-nikitsin commented on src/components/AppContainer/AppContainer.js
> +  };
Sorry( 
Already fixed.

2020-09-24 17:31 UTC, artur-nikitsin commented on src/components/Header/Header.js
> +      {props.isLogin ? <button className='logoutButton' onClick={props.handleLogout}>Logout</button> : null}
Fixed

2020-09-24 17:33 UTC, artur-nikitsin commented on src/components/LoginForm/LoginForm.js
> +function LoginForm(props) {
Fixed

2020-09-24 17:33 UTC, artur-nikitsin commented on src/components/MemberTracks/MemberTracks.js
> +class MemberTracks extends React.Component {
Fixed

2020-09-24 17:34 UTC, artur-nikitsin commented on src/components/MemberTracks/MemberTracks.js
> +
Fixed

2020-09-24 17:37 UTC, artur-nikitsin commented on src/components/MemberTracks/MemberTracks.js
> +          <p className={"userGreeting"}>{`Hi, dear '${this.props.userName}! This is your task tracks:`}</p>
Fixed

2020-09-24 17:40 UTC, artur-nikitsin commented on src/components/Modals/Common/ModalElements/RadioInput.js
> +        /*  className={`radioInput ${this.props.status}`}*/
Fixed

2020-09-24 17:50 UTC, artur-nikitsin commented on src/components/Modals/Common/ModalElements/RadioInput.js
> +          onChange={this.props.handleRadioInput}
Fixed

2020-09-24 17:57 UTC, artur-nikitsin commented on src/components/Modals/Common/ModalElements/TextInput.js
> +
Fixed

2020-09-24 18:05 UTC, artur-nikitsin commented on src/components/Modals/Common/ModalElements/TextInput.js
> +        this.props.handleValidInput(this.props.inputName, validatorsManager(this.props.inputName, this.props.value).isValid);
Fixed

2020-09-24 18:08 UTC, artur-nikitsin commented on src/components/Modals/Common/ModalElements/TextInput.js
> +          status: validatorsManager(this.props.inputName, this.props.value).status
Fixed

2020-09-24 18:11 UTC, artur-nikitsin commented on src/components/Modals/Common/ModalElements/TextInput.js
> +
Fixed

2020-09-24 19:32 UTC, artur-nikitsin commented on src/components/Footer/Footer.js
> +    <p className='allRights'>DIMS-2020. All rights reversed ©</p>
Fixed

2020-09-25 07:24 UTC, artur-nikitsin commented on src/components/LoginForm/LoginForm.js
> +          <li><label htmlFor="">Password:</label><input type="password" /></li>
Fixed

2020-09-25 07:47 UTC, artur-nikitsin commented on src/components/LoginForm/LoginForm.js
> +                     onClick={props.handleLogin} /></li>
Fixed

2020-09-25 07:50 UTC, artur-nikitsin commented on src/components/LoginForm/loginForm.scss
> +      input {
Fixed

2020-09-25 07:51 UTC, artur-nikitsin commented on src/components/MemberTracks/MemberTracks.js
> +                <a href=''>{track.name}</a>
Fixed

2020-09-25 07:52 UTC, artur-nikitsin commented on src/components/Members/MembersPage.js
>  class MembersPage extends React.Component {
Fixed

2020-09-25 07:55 UTC, artur-nikitsin commented on src/components/Members/MembersPage.js
> +      if (status === 'OK') {
Fixed

2020-09-25 08:00 UTC, artur-nikitsin commented on src/components/Modals/Common/UsersModalDataWorker.js
> +      [event.target.name]: event.target.value,
Fixed

2020-09-25 09:04 UTC, artur-nikitsin commented on src/components/Modals/Common/UsersModalDataWorker.js
> +        skype: this.props.userData.skype
I revrited as a method

2020-09-25 10:30 UTC, artur-nikitsin commented on src/components/Modals/Common/UsersModalDataWorker.js
> +                       isSubmit={this.state.isSubmit} />
Fixed

2020-09-25 10:30 UTC, artur-nikitsin commented on src/components/Modals/Common/UsersModalDataWorker.js
> +                       isSubmit={this.state.isSubmit} />
Fixed

2020-09-25 10:31 UTC, artur-nikitsin commented on src/components/Sidebar/SideBar.js
> +function SideBar(props) {
Fixed

2020-09-25 10:31 UTC, artur-nikitsin commented on src/components/helpers/getLocaleDate/getLocalDate.js
> +import React from "react";
Fixed

2020-09-25 10:31 UTC, artur-nikitsin commented on src/components/helpers/getLocaleDate/getLocalDate.test.js
> +import React from "react";
Fixed

2020-09-25 10:32 UTC, artur-nikitsin commented on src/components/helpers/getSubString/getSubString.js
> +import React from 'react';
Fixed

2020-09-25 10:32 UTC, artur-nikitsin commented on src/components/helpers/getSubString/getSubString.test.js
> +import React from "react";
Fixed

2020-09-25 10:41 UTC, artur-nikitsin commented on src/components/helpers/validators/lengthValidator.js
> +  if (props.length > 2) {
Because this is a method that checks the number of characters

2020-09-25 10:43 UTC, artur-nikitsin commented on src/components/helpers/validators/lengthValidator.js
> +import React from "react";
Fixed

2020-09-26 16:12 UTC, maximsan commented on src/components/Modals/Common/UsersModalDataWorker.js
> +        skype: this.props.userData.skype
I don't know, let me see it on Tuesday

2020-09-26 16:13 UTC, maximsan commented on src/components/helpers/validators/lengthValidator.js
> +  if (props.length > 2) {
as I said no need to pass props object, pass just length variable

2020-09-27 16:00 UTC, artur-nikitsin commented on src/components/Modals/Common/UsersModalDataWorker.js
> +    }
Fixed

2020-09-27 16:03 UTC, artur-nikitsin commented on src/components/Modals/Common/UsersModalDataWorker.js
> +        });
Fixed

2020-09-27 16:03 UTC, artur-nikitsin commented on src/components/helpers/getLocaleDate/getLocalDate.test.js
> +    //Assert - checking
Fixed

2020-09-27 17:29 UTC, artur-nikitsin commented on src/components/helpers/validators/lengthValidator.js
> +  if (props.length > 2) {
This props contains only one string. Fixed

2020-09-27 18:05 UTC, artur-nikitsin commented on src/components/helpers/validators/lastNameValidator.js
> +function lastNameValidator(props) {
Fixed

2020-09-27 18:05 UTC, artur-nikitsin commented on src/components/helpers/validators/emailValidator.js
> +function emailValidator(props) {
Fixed

2020-09-27 18:05 UTC, artur-nikitsin commented on src/components/helpers/validators/nameValidator.js
> +    if (regExpTester(nameRegexp, props)) {
Fixed

2020-09-27 18:05 UTC, artur-nikitsin commented on src/components/helpers/validators/regExpTester.js
> +};
Fixed

2020-09-27 20:14 UTC, artur-nikitsin commented on src/components/helpers/validators/mobilePhoneValidator.js
> +    if (regExpTester(phoneNumberRegexp, props)) {
Fixed

2020-09-28 19:53 UTC, maximsan requested changes
Hello, be accurate. It looks better, but I still see drawbacks. Please, fix and update pr. Thanks!

2020-09-28 19:53 UTC, maximsan commented on src/components/LoginForm/LoginForm.js
> +      isSubmit: false
why do you need it here ? it looks weird

2020-09-28 19:53 UTC, maximsan commented on src/components/LoginForm/LoginForm.js
> +    }
It looks not good. I believe you can do it better

2020-09-28 19:53 UTC, maximsan commented on src/components/LoginForm/LoginForm.js
> +  };
Why do you need it here ? it should be in state or in helper outside of component

2020-09-28 19:53 UTC, maximsan commented on src/components/LoginForm/LoginForm.js
> +                           handleValidInput={this.handleValidInput} /></li>
you can do validation directly in `handleChange`

2020-09-28 19:53 UTC, maximsan commented on src/components/MemberProfile/MemberProfile.js
> +      activePage: page
use just the same `activePage` for shortness

2020-09-28 19:53 UTC, maximsan commented on src/components/MemberTracks/MemberTracks.js
> +    );
if you don't use it for any iteration, what is the point to save it in variable? in that case you can import it from other file

2020-09-28 19:53 UTC, maximsan commented on src/components/Members/MembersPage.js
> +    } else return null;
no need to write else

2020-09-28 19:53 UTC, maximsan commented on src/components/Members/MembersPage.js
> +    } else return null;
no need to write else

2020-09-28 19:53 UTC, maximsan commented on src/components/Modals/Common/ModalElements/InputListCreator.js
> +    const data = this.props.modalData;
do spreading

2020-09-28 19:53 UTC, maximsan commented on src/components/Modals/Common/ModalElements/InputListCreator.js
> +      const sexValue = data.sex;
do spreading

2020-09-28 19:53 UTC, maximsan commented on src/components/Modals/Common/ModalElements/InputListCreator.js
> +        inputList.push(
don't use mutable methods

2020-09-28 19:53 UTC, maximsan commented on src/components/Modals/Common/ModalElements/InputListCreator.js
> +        inputList.push(
don't use mutable methods

2020-09-28 19:53 UTC, maximsan commented on src/components/Modals/Common/ModalElements/InputListCreator.js
> +    for (let input in this.props.modalTemplate) {
use `forEach/map/reduce` and etc instead of `for in` cycle

2020-09-28 19:53 UTC, maximsan commented on src/components/Modals/UserEditModal/UserEditModal.js
> +class UserEditModal extends React.Component {
PureComponent ?

2020-09-28 19:53 UTC, maximsan commented on src/components/Modals/UserRegisterModal/UserRegisterModal.js
> +  }
why do you need `ctor` here ?

2020-09-28 19:53 UTC, maximsan commented on src/components/common/Inputs/RadioInput.js
> +class RadioInput extends React.Component {
PureComponent ?

2020-09-28 19:53 UTC, maximsan commented on src/components/helpers/DataExtractor/dataExtractor.js
> +  }
use reduce

2020-09-28 19:53 UTC, maximsan commented on src/components/helpers/FormValidator/formValidator.js
> +  }
use reduce/map

2020-09-28 19:53 UTC, maximsan commented on src/components/helpers/FormValidator/formValidator.test.js
> +    expect(actual).toStrictEqual(expected);
I believe `toEqual` is enough

2020-09-28 19:53 UTC, maximsan commented on src/components/helpers/FormValidator/formValidator.test.js
> +describe("func returns local date format", () => {
here you write common phrase

2020-09-28 19:53 UTC, maximsan commented on src/components/helpers/FormValidator/formValidator.test.js
> +  test("false should be returned", () => {
in test or it you should write something like continuation of this common phrase

2020-09-28 19:53 UTC, maximsan commented on src/components/helpers/validators/lengthValidator.js
> +  } else {
no need to write else

2020-09-29 06:26 UTC, artur-nikitsin commented on src/components/Members/MembersPage.js
> +    } else return null;
Fixed

2020-09-29 06:26 UTC, artur-nikitsin commented on src/components/Members/MembersPage.js
> +    } else return null;
Fixed

2020-09-29 06:29 UTC, artur-nikitsin commented on src/components/Modals/Common/ModalElements/InputListCreator.js
> +    const data = this.props.modalData;
Fixed

2020-09-29 06:29 UTC, artur-nikitsin commented on src/components/Modals/Common/ModalElements/InputListCreator.js
> +      const sexValue = data.sex;
Fixed

2020-09-29 06:46 UTC, artur-nikitsin commented on src/components/helpers/validators/lengthValidator.js
> +  } else {
Fixed

2020-09-29 06:55 UTC, artur-nikitsin commented on src/components/common/Inputs/RadioInput.js
> +class RadioInput extends React.Component {
Fixed

2020-09-29 06:56 UTC, artur-nikitsin commented on src/components/Modals/UserRegisterModal/UserRegisterModal.js
> +  }
Fixed

2020-09-29 06:57 UTC, artur-nikitsin commented on src/components/Modals/UserEditModal/UserEditModal.js
> +class UserEditModal extends React.Component {
Fixed

2020-10-01 15:19 UTC, artur-nikitsin commented on src/components/helpers/FormValidator/formValidator.test.js
> +describe("func returns local date format", () => {
Fixed

2020-10-01 15:37 UTC, artur-nikitsin commented on src/components/LoginForm/LoginForm.js
> +      isSubmit: false
Fixed

2020-10-01 15:37 UTC, artur-nikitsin commented on src/components/LoginForm/LoginForm.js
> +    }
Fixed

2020-10-01 15:38 UTC, artur-nikitsin commented on src/components/LoginForm/LoginForm.js
> +  };
Fixed

2020-10-01 15:40 UTC, artur-nikitsin commented on src/components/LoginForm/LoginForm.js
> +                           handleValidInput={this.handleValidInput} /></li>
I do this in the root handler to do more complex validation, get data from child components, and display different warnings depending on the type of input.

2020-10-01 15:41 UTC, artur-nikitsin commented on src/components/MemberProfile/MemberProfile.js
> +      activePage: page
Fixed

2020-10-01 15:43 UTC, artur-nikitsin commented on src/components/helpers/FormValidator/formValidator.test.js
> +  test("false should be returned", () => {
Fixed

2020-10-01 17:51 UTC, artur-nikitsin commented on src/components/MemberTracks/MemberTracks.js
> +    );
Fixed

2020-10-01 17:51 UTC, artur-nikitsin commented on src/components/MemberTracks/MemberTracks.js
> +    );
Fixed

2020-10-01 17:51 UTC, artur-nikitsin commented on src/components/Modals/Common/ModalElements/InputListCreator.js
> +        inputList.push(
Fixed

2020-10-01 17:51 UTC, artur-nikitsin commented on src/components/Modals/Common/ModalElements/InputListCreator.js
> +        inputList.push(
Fixed

2020-10-01 17:51 UTC, artur-nikitsin commented on src/components/Modals/Common/ModalElements/InputListCreator.js
> +    for (let input in this.props.modalTemplate) {
Fixed

2020-10-01 17:51 UTC, artur-nikitsin commented on src/components/helpers/DataExtractor/dataExtractor.js
> +  }
Fixed

2020-10-01 19:12 UTC, artur-nikitsin commented on src/components/LoginForm/LoginForm.js
> +    });
Fixed

2020-10-01 19:13 UTC, artur-nikitsin commented on src/components/MemberTracks/MemberTracks.js
> +
Fixed

2020-10-01 19:14 UTC, artur-nikitsin commented on src/components/Modals/Common/ModalElements/inputListCreator.scss
> +}*/
Fixed

2020-10-01 19:31 UTC, artur-nikitsin commented on src/components/Modals/User/UsersModalDataWorker.js
> +    const _thisState = this.state;
Fixed

2020-10-01 19:32 UTC, artur-nikitsin commented on src/components/Modals/User/UsersModalDataWorker.js
> +    const _thisState = this.state;
Fixed

2020-10-01 19:37 UTC, artur-nikitsin commented on src/components/common/Inputs/TextInput.js
> +    const prevValue = prevProps.value;
I cannot do this because I only compare the "value" parameters of the latest and newest props. And these variables will have the same names

2020-10-01 19:52 UTC, artur-nikitsin commented on src/components/helpers/FormValidator/formValidator.js
> +  return !statusArr.includes(false || null);
Rewrote using the sort method, because I need to check the array for at least one value. I don't need a new array

2020-10-01 20:44 UTC, maximsan approved these changes
Perfect!

2020-10-01 20:45 UTC, merged